name: Main

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tick
        run: |
          echo "Hoje $(date), fugiram mais Leopardinhos!" > README.md
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git init
          git branch -m master
          git add README.md
          git commit -m "Alteração $(date) feita por ${GITHUB_ACTOR}"
          git push -u origin HEAD:master
